"use client"

// 

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import Providers from '@/components/Providers'

import ProviderNextAuth from "@/components/ProviderNextAuth";
import AppBar from "@/components/AppBar";

const inter = Inter({ subsets: ["latin"] });
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderNextAuth>
          <AppBar />
          <div className={inter.className}>{children}</div>
        </ProviderNextAuth>
      </body>
    </html>
  );
}

export default RootLayout;