"use client"

// 

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppBar, { Header } from "@/components/AppBar";

import toast, { Toaster } from 'react-hot-toast';

import "react-loading-skeleton/dist/skeleton.css";
import React from "react";
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/


interface IRenderWithNav {
  children: React.ReactNode
}

const RenderWithNav = (props: IRenderWithNav) => {
  return (<>
    <Header />
    <section className="flex flex-row">
      <AppBar />
      <Toaster />
      <div className={`${inter.className} grow`}>{props.children}</div>
    </section>
  </>);
}

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname()
  console.log("pathname : ", pathname)

  return (
    <html lang="en">
      <body className="flex flex-col">
        {(pathname.startsWith("/view/")) ?
          <div className={`${inter.className} grow`}>{children}</div>
          :
          <RenderWithNav>
            <div className={`${inter.className} grow`}>{children}</div>
          </RenderWithNav>}
      </body>
    </html>
  );
}

export default RootLayout;