"use client"

// 

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import Providers from '@/components/Providers'

import ProviderNextAuth from "@/components/ProviderNextAuth";
import AppBar, { Header } from "@/components/AppBar";

import "react-loading-skeleton/dist/skeleton.css";


const inter = Inter({ subsets: ["latin"] });
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <ProviderNextAuth>
          <Header />
          <section className="flex flex-row">
            <AppBar />
            <div className={`${inter.className} grow`}>{children}</div>
          </section>
        </ProviderNextAuth>
      </body>
    </html>
  );
}

export default RootLayout;